### PR TITLE
#13 - Added isDone and isComplete selector feature

### PR DESCRIPTION
**Pull request by sebastianjg**
I encountered a case where it was suitable to solve with a hasSuccess-selector, as mentioned in #13, so I went ahead and added it.

Excellent work with the [Arc](https://github.com/diegohaz/arc) repository, really appreciate it!

### CODE REVIEW

**Comment by diegohaz** [comment]
Hi, @sebastianjg. Excellent work. Thank you so much.

I'm just not sure about the name. My English isn't the best, but `hasSuccess` seems strange. Do people say `it has success...`?

What do you think?

cc/ @Geczy

**Comment by Geczy** [comment]
* `isPending`
* `hasFailed`

* `isDone` for success
* `isComplete` for an _always_ function

http://api.jquery.com/jquery.ajax/

**Comment by diegohaz** [comment]
`isDone` seems good.

**Comment by Geczy** [comment]
What about just pending, failed, done, complete? 

Without the prefix?

**Comment by diegohaz** [comment]
@Geczy I like it, but let's discuss that on another thread. For this PR, just changing `hasSuccess` to `isDone` is 👍.

@sebastianjg

**Comment by sebastianjg** [comment]
Thanks for the feedback guys! I agree that `isDone` is better (a bit hasty on my end as a non-native english speaker). 

I have updated the PR.

**Comment by diegohaz** [comment]
Thank you, @sebastianjg

**Pull request merged**
